/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package destruct;

import java.awt.Rectangle;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.ByteBuffer;
import javax.swing.JFrame;

/**
 *
 * @author John
 */
public class ServerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents(); 
        System.setErr(new PrintStream(new OutputStream() {
            ByteBuffer bytes = ByteBuffer.allocate(1000);
            @Override
            public void write(int b) throws IOException {
                bytes.put((byte)b);
                flush();
            }
            @Override
            public void flush()
            {
                byte[] size = new byte[bytes.position()];
                System.arraycopy(bytes.array(), 0, size, 0, size.length);
                outputBox.setText(outputBox.getText()+new String(size));
                bytes = ByteBuffer.allocate(1000);
                outputBox.scrollRectToVisible(
                new Rectangle(0,outputBox.getHeight()+5000,1,1));
            }
        })
        {
            @Override
            public void println(Object e)
            {
                print(e+"\n");
            }
            @Override
            public void println(String e)
            {
                print(e+"\n");
            }
        });
        //System.err.println("WAFFLES!");//System.err.flush();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputBox.setBackground(new java.awt.Color(0, 0, 0));
        outputBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.green, java.awt.Color.white));
        outputBox.setFont(new java.awt.Font("FangSong", 1, 12)); // NOI18N
        outputBox.setForeground(new java.awt.Color(255, 0, 51));
        outputBox.setAutoscrolls(false);
        outputBox.setCaretColor(new java.awt.Color(255, 255, 255));
        outputBox.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(outputBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane outputBox;
    // End of variables declaration//GEN-END:variables

}
